export interface ShiftingImage {
  id: string;
  src: string;
  project: string;
  title: string;
  projectSlug: string;
}

export const landingShiftingImages: ShiftingImage[] = [
  {
    id: "2",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/lifePath/interactive-content-creation.webp?quality=50",
    project: "Light Path Learning",
    title: "Interactive Assignments",
    projectSlug: "light-path-learning",
  },
  {
    id: "3",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/lifePath/update-grade.webp?quality=50",
    project: "Light Path Learning",
    title: "AI Grading with Oversight",
    projectSlug: "light-path-learning",
  },
  {
    id: "6",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/lifePath/comprehensive-administration.webp?quality=50",
    project: "Light Path Learning",
    title: "Administrative Controls",
    projectSlug: "light-path-learning",
  },
  {
    id: "7",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/lifePath/assignment-notes.webp?quality=50",
    project: "Light Path Learning",
    title: "Communication",
    projectSlug: "light-path-learning",
  },
  {
    id: "8",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/lifePath/youtube-integration.webp?quality=50",
    project: "Light Path Learning",
    title: "YouTube Integration",
    projectSlug: "light-path-learning",
  },
  {
    id: "9",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/lifePath/library.webp?quality=50",
    project: "Light Path Learning",
    title: "Library and Reference Materials",
    projectSlug: "light-path-learning",
  },
  {
    id: "10",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/lifePath/todays-assignments.webp?quality=50",
    project: "Light Path Learning",
    title: "Daily Assignments",
    projectSlug: "light-path-learning",
  },
  {
    id: "13",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/lifePath/fun-zone.webp?quality=50",
    project: "Light Path Learning",
    title: "Fun Zone",
    projectSlug: "light-path-learning",
  },
  {
    id: "14",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/lifePath/assistant-chat.webp?quality=50",
    project: "Light Path Learning",
    title: "Always-Available AI Assistant",
    projectSlug: "light-path-learning",
  },
  {
    id: "23",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dark-violet-divinations-portfolio-image-2.png",
    project: "Dark Violet Divinations",
    title: "Divinations welcome screen.",
    projectSlug: "dark-violet-divinations",
  },
  {
    id: "24",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dark-violet-divinations-portfolio-image-3.png",
    project: "Dark Violet Divinations",
    title: "Quantum entanglement and divination explained.",
    projectSlug: "dark-violet-divinations",
  },
  {
    id: "26",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dark-violet-divinations-portfolio-image-5.png",
    project: "Dark Violet Divinations",
    title: "Oracle card images.",
    projectSlug: "dark-violet-divinations",
  },
  {
    id: "27",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dark-violet-divinations-portfolio-image-6.png",
    project: "Dark Violet Divinations",
    title: "Oracle card overview",
    projectSlug: "dark-violet-divinations",
  },
  {
    id: "29",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dark-violet-divinations-portfolio-image-8.png",
    project: "Dark Violet Divinations",
    title: "Summoning the oracles.",
    projectSlug: "dark-violet-divinations",
  },
  {
    id: "32",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dark-violet-divinations-portfolio-image-11.png",
    project: "Dark Violet Divinations",
    title: "Oracle and attribute revealed.",
    projectSlug: "dark-violet-divinations",
  },
  {
    id: "33",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dark-violet-divinations-portfolio-image-12.png",
    project: "Dark Violet Divinations",
    title: "Multiple oracle divination.",
    projectSlug: "dark-violet-divinations",
  },
  {
    id: "34",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dark-violet-divinations-portfolio-image-13.png",
    project: "Dark Violet Divinations",
    title: "Dark Violet comtemplating the divination.",
    projectSlug: "dark-violet-divinations",
  },
  {
    id: "37",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dark-violet-divinations-portfolio-image-16.png",
    project: "Dark Violet Divinations",
    title: "Divination summary and report.",
    projectSlug: "dark-violet-divinations",
  },
  {
    id: "38",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/space-weather-portfolio-image-1.png",
    project: "Space Weather",
    title: "Latest EUV images of the Sun.",
    projectSlug: "space-weather",
  },
  {
    id: "39",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/space-weather-portfolio-image-2.png",
    project: "Space Weather",
    title: "Full size image of the Sun.",
    projectSlug: "space-weather",
  },
  {
    id: "40",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/space-weather-portfolio-image-3.png",
    project: "Space Weather",
    title: "Dashboard graphs and charts.",
    projectSlug: "space-weather",
  },
  {
    id: "41",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/space-weather-portfolio-image-4.png",
    project: "Space Weather",
    title: "Full view of graph.",
    projectSlug: "space-weather",
  },
  {
    id: "42",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/space-weather-portfolio-image-5.png",
    project: "Space Weather",
    title: "Solar activity monitoring further.",
    projectSlug: "space-weather",
  },
  {
    id: "43",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/space-weather-portfolio-image-6.png",
    project: "Space Weather",
    title: "Full view of solar activity monitoring.",
    projectSlug: "space-weather",
  },
  {
    id: "46",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/chatter-front.png",
    project: "Chatter.DarkViolet.ai",
    title: "Front Page",
    projectSlug: "chatter",
  },
  {
    id: "47",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/chatter-characters-main.png",
    project: "Chatter.DarkViolet.ai",
    title: "Characters Menu",
    projectSlug: "chatter",
  },
  {
    id: "51",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/chatter-voice-chat.png",
    project: "Chatter.DarkViolet.ai",
    title: "Voice Chat",
    projectSlug: "chatter",
  },
  {
    id: "52",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/chatter-scenario.png",
    project: "Chatter.DarkViolet.ai",
    title: "Create a Scenario",
    projectSlug: "chatter",
  },
  {
    id: "56",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-login.png",
    project: "Dark Violet Art",
    title: "Login",
    projectSlug: "dark-violet-art",
  },
  {
    id: "57",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-mainfeed.png",
    project: "Dark Violet Art",
    title: "Main Feed",
    projectSlug: "dark-violet-art",
  },
  {
    id: "58",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-viewimage.png",
    project: "Dark Violet Art",
    title: "Image View",
    projectSlug: "dark-violet-art",
  },
  {
    id: "60",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-boostimage.png",
    project: "Dark Violet Art",
    title: "Boost",
    projectSlug: "dark-violet-art",
  },
  {
    id: "61",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-viewthought.png",
    project: "Dark Violet Art",
    title: "Thought",
    projectSlug: "dark-violet-art",
  },
  {
    id: "62",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-notifications.png",
    project: "Dark Violet Art",
    title: "Notifications",
    projectSlug: "dark-violet-art",
  },
  {
    id: "63",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-userprofile.png",
    project: "Dark Violet Art",
    title: "Profile",
    projectSlug: "dark-violet-art",
  },
  {
    id: "64",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-usergalleries.png",
    project: "Dark Violet Art",
    title: "Galleries",
    projectSlug: "dark-violet-art",
  },
  {
    id: "65",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-editprofile.png",
    project: "Dark Violet Art",
    title: "Edit Profile",
    projectSlug: "dark-violet-art",
  },
  {
    id: "67",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dvart-mainmenu.png",
    project: "Dark Violet Art",
    title: "Main Menu",
    projectSlug: "dark-violet-art",
  },
  {
    id: "68",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/moth-ramen-main.png",
    project: "MothRamen",
    title: "Welcome Banner",
    projectSlug: "moth-ramen",
  },
  {
    id: "69",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/moth-ramen-images.png",
    project: "MothRamen",
    title: "Parallax Images",
    projectSlug: "moth-ramen",
  },
  {
    id: "70",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/moth-ramen-menu.png",
    project: "MothRamen",
    title: "Menu",
    projectSlug: "moth-ramen",
  },
  {
    id: "71",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/moth-ramen-merch-banner.png",
    project: "MothRamen",
    title: "Merch Banner",
    projectSlug: "moth-ramen",
  },
  {
    id: "72",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/moth-ramen-merch-item-1.png",
    project: "MothRamen",
    title: "Merch Page",
    projectSlug: "moth-ramen",
  },
  {
    id: "73",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/moth-ramen-merch-item-2.png",
    project: "MothRamen",
    title: "Sake Set",
    projectSlug: "moth-ramen",
  },
  {
    id: "75",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/moth-ramen-merch-item-4.png",
    project: "MothRamen",
    title: "Women's Hoodie",
    projectSlug: "moth-ramen",
  },
  {
    id: "76",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dat-index.png",
    project: "Do-A-Thing",
    title: "Welcome",
    projectSlug: "do-a-thing",
  },
  {
    id: "79",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dat-thinglist.png",
    project: "Do-A-Thing",
    title: "Thing List",
    projectSlug: "do-a-thing",
  },
  {
    id: "81",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dat-editthing.png",
    project: "Do-A-Thing",
    title: "Edit Thing",
    projectSlug: "do-a-thing",
  },
  {
    id: "82",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dat-newthing.png",
    project: "Do-A-Thing",
    title: "New Thing Chat",
    projectSlug: "do-a-thing",
  },
  {
    id: "84",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dat-friends.png",
    project: "Do-A-Thing",
    title: "User Friends",
    projectSlug: "do-a-thing",
  },
  {
    id: "85",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dat-userthings.png",
    project: "Do-A-Thing",
    title: "User Things",
    projectSlug: "do-a-thing",
  },
  {
    id: "87",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dat-viewbadge.png",
    project: "Do-A-Thing",
    title: "View Badge",
    projectSlug: "do-a-thing",
  },
  {
    id: "88",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dat-chooseavatar.png",
    project: "Do-A-Thing",
    title: "Choose Avatar",
    projectSlug: "do-a-thing",
  },
  {
    id: "91",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dat-leaderboards.png",
    project: "Do-A-Thing",
    title: "Leaderboard",
    projectSlug: "do-a-thing",
  },
  {
    id: "93",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/launchpad-1-index.png",
    project: "Remix Launchpad",
    title: "Welcome",
    projectSlug: "remix-launchpad",
  },

  {
    id: "106",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/launchpad-14-components3.png",
    project: "Remix Launchpad",
    title: "Components",
    projectSlug: "remix-launchpad",
  },

  {
    id: "111",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/launchpad-19-masonrygriddemo.png",
    project: "Remix Launchpad",
    title: "Masonry Grid Demo",
    projectSlug: "remix-launchpad",
  },
  {
    id: "113",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/ihc-index.png",
    project: "I💜Components",
    title: "Welcome",
    projectSlug: "i-heart-components",
  },
  {
    id: "114",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/ihc-mainmenu.png",
    project: "I💜Components",
    title: "Main Menu",
    projectSlug: "i-heart-components",
  },
  {
    id: "115",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/ihc-uiux.png",
    project: "I💜Components",
    title: "UI / UX",
    projectSlug: "i-heart-components",
  },
  {
    id: "118",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/ihc-uiux.png",
    project: "I💜Components",
    title: "Projects",
    projectSlug: "i-heart-components",
  },
  {
    id: "121",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/ihc-dustin.png",
    project: "I💜Components",
    title: "Dustin Carr",
    projectSlug: "i-heart-components",
  },

  {
    id: "123",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/ihc-evan.png",
    project: "I💜Components",
    title: "Evan Marie",
    projectSlug: "i-heart-components",
  },

  {
    id: "126",
    src: "https://mhejreuxaxxodkdlfcoq.supabase.co/storage/v1/render/image/public/darkVioletPublic/landing/dreams-index.png",
    project: "Dreams AI",
    title: "Dreams AI - Input Dream",
    projectSlug: "dreams-ai",
  },
];

export const shuffledShiftingImages = landingShiftingImages.sort(
  () => Math.random() - 0.5
);
